services:
  aas:
    restart: unless-stopped
    image: faaast-server-arm:1.1.0
    ports:
      - 4840:4840
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./faaast:/faaast
    environment:
      faaast_model: /faaast/pick-and-place.aasx
      faaast_config: /faaast/config-opcua-http.json
      faaast_loglevel_faaast: DEBUG
      faaast_config_extension_assetConnections[0]_baseUrl: http://integration-app:8080
    depends_on:
      - integration-app

  integration-app:
    restart: unless-stopped
    image: integration-app:1.0
    ports:
      - 8080:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      ROBOT_IP_ADDRESS: "192.168.3.11"
      ROBOT_PORT: 502
