services:
  aas-opcua-http: #TODO change this
    image: fraunhoferiosb/faaast-service:1.1 
    # image: faaast-server-arm:1.1.0
    ports:
      - 4840:4840
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/charles/repos/project-ss/aas/faaast:/faaast
    environment:
      faaast_model: /faaast/pick-and-place.aasx
      faaast_config: /faaast/config-opcua-http.json
      faaast_loglevel_faaast: DEBUG
      faaast_config_extension_assetConnections[0]_baseUrl: http://integration-api:8080
    depends_on:
      - integration-api

  integration-api:
    image: integration-api:1.0
    ports:
      - 8080:8080
    # devices: # TODO this is required on deployment
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      ROBOT_IP_ADDRESS: "192.168.3.11"
      ROBOT_PORT: 502
