version: '3.4'
services:
  faaast-opcua:
    image: fraunhoferiosb/faaast-service:latest
    ports:
      - 4840:4840
      - 8080:8080
      - 443:443
    volumes:
      - /home/charles/repos/project-ss/faaast/aasx:/aasx
    environment:
      # faaast_model: /aasx/Honeywell-TC500A-v3.aasx
      faaast_model: /aasx/test-model.aasx
      faaast_config: /aasx/config-opcua-http.json
      # faaast_loglevel_external: INFO
      faaast_loglevel_faaast: DEBUG
      # faaast_no_validation: ""