services:
  aas-opcua-http: #TODO change this
    image: fraunhoferiosb/faaast-service:1.1 
    # image: faaast-server-arm:1.1.0
    ports:
      - 4840:4840
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/charles/repos/project-ss/aas/faaast:/faaast
    environment:
      faaast_model: /faaast/test-model.aasx
      faaast_config: /faaast/config-opcua-http.json
      faaast_loglevel_faaast: DEBUG

      faaast_config_extension_assetConnections[0]_baseUrl: http://host.docker.internal:8080
