services:
  integration-api:
    image: integration-app:1.0
    ports:
      - 8080:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      ROBOT_IP_ADDRESS: "192.168.3.11"
      ROBOT_PORT: 502

